#! /bin/sh 
#
# Change the value of ORACLE_HOME to specify the correct Oracle home
# directory for your installation.

ORACLE_HOME=/u01/app/oracle/product/12.1.0/db_1
#
# Change the value of ORACLE to the login name of the
# oracle owner at your site.
#
ORACLE=oracle

PATH=${PATH}:$ORACLE_HOME/bin
HOST=`hostname`
PLATFORM=`uname`
export ORACLE_HOME PATH
#
if [ ! "$2" = "ORA_DB" ] ; then
      runuser -l $ORACLE  $0 $1 ORA_DB
      if [ "$PLATFORM" = "Linux" ] && [ "$1" = "start" ] ; then
         touch /var/lock/subsys/dbora
        elif [ "$PLATFORM" = "Linux" ] && [ "$1" = "stop" ] ; then
          rm -f /var/lock/subsys/dbora
      fi
      exit
   fi
#
case $1 in
'start')
        $ORACLE_HOME/bin/dbstart $ORACLE_HOME &
        ;;
'stop')
        $ORACLE_HOME/bin/dbshut $ORACLE_HOME &
        rm -f /var/lock/subsys/dbora
        ;;
*)
        echo "usage: $0 {start|stop}"
        exit
        ;;
esac
#
exit
